// <auto-generated />
using MaritimeManager.Infra.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MaritimeManager.Infra.Migrations
{
    [DbContext(typeof(MaritimeDbContext))]
    [Migration("20251115135648_CorrectPointOfInterestColumnOrder")]
    partial class CorrectPointOfInterestColumnOrder
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MaritimeManager.Domain.Entities.PointOfInterest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnOrder(0);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(3);

                    b.Property<string>("Identifier")
                        .HasColumnType("TEXT")
                        .HasColumnOrder(1);

                    b.Property<double>("Latitude")
                        .HasColumnType("REAL")
                        .HasColumnOrder(4);

                    b.Property<double>("Longitude")
                        .HasColumnType("REAL")
                        .HasColumnOrder(5);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(2);

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnOrder(6);

                    b.HasKey("Id");

                    b.ToTable("PointsOfInterest");
                });
#pragma warning restore 612, 618
        }
    }
}
